name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: set up env
        run: python -m pip install -e .

      # Execute unit tests
      - name: test
        run: pytest

      # Check coverage (less coverage required here since vizard is not tested)
      - name: test coverage
        run: pytest --cov=src --cov-fail-under=70

  black-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: install black
        run: python -m pip install black[jupyter]==21.11b1

      # Run black
      - name: run black
        run: black --check .
