name: Continuous Integration and Deployment
on: 
  push: 
    branches: [ main ]
  pull_request:
  schedule:
    - cron:  "0 3 * * 1" # Run every Monday 3 am

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up env
        run: python -m pip install -e .[docs,dev]

      - name: Run black
        run: black --check .

      - name: Run isort
        run: isort .

      - name: Run pylint for mdp folder
        run: pylint src/behavior_generation_lecture_python/mdp --errors-only

      - name: Run mypy for mdp folder
        run: mypy src/behavior_generation_lecture_python/mdp

      - name: Test
        run: |
          export DISPLAY=:99
          Xvfb :99 &
          pytest

      - name: Check coverage
        run: |
          export DISPLAY=:99
          Xvfb :99 &
          pytest --cov=src --cov-fail-under=85

      - name: Copy notebooks to docs folder
        run: cp -r notebooks/* docs/notebooks

      - name: Build docs
        run: mkdocs build

  deploy-pages:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main'
    concurrency: deploy-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up env
        run: python -m pip install -e .[docs]

      - name: Copy notebooks to docs folder
        run: cp -r notebooks/* docs/notebooks

      - run: mkdocs gh-deploy --force


