name: Continuous Integration and Deployment
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: install black
        run: python -m pip install black[jupyter]==21.11b1

      - name: run black
        run: black --check .

      - name: set up env
        run: python -m pip install -e .

      - name: test
        run: pytest

      - name: check coverage # (less coverage required here since vizard is not tested)
        run: pytest --cov=src --cov-fail-under=70

      - name: copy notebooks to docs folder
        run: cp -r notebooks/* docs/notebooks

      - name: build docs
        run: mkdocs build

  deploy-pages:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/feature/mkdocs' # todo: change to main
    concurrency: deploy-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: set up env
        run: python -m pip install -e .

      - name: copy notebooks to docs folder
        run: cp -r notebooks/* docs/notebooks

      - run: mkdocs gh-deploy --force


