name: Continuous Integration and Deployment
on: 
  push: 
    branches: [ main ]
  pull_request:
  schedule:
    - cron:  "0 3 * * 1" # Run every Monday 3 am

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.10"

      - name: Set up env
        run: uv sync --all-extras

      - name: Run ruff format
        run: ruff format

      - name: Run ruff linter for mdp folder
        run: ruff check src/behavior_generation_lecture_python/mdp

      - name: Run mypy for mdp folder
        run: mypy src/behavior_generation_lecture_python/mdp

      - name: Test
        run: |
          export DISPLAY=:99
          Xvfb :99 &
          uv run pytest

      - name: Check coverage
        run: |
          export DISPLAY=:99
          Xvfb :99 &
          uv run pytest --cov=src --cov-fail-under=85

      - name: Copy notebooks to docs folder
        run: cp -r notebooks/* docs/notebooks

      - name: Build docs
        run: uv run mkdocs build

  deploy-pages:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main'
    concurrency: deploy-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.10"

      - name: Set up env
        run: uv sync --all-extras

      - name: Copy notebooks to docs folder
        run: cp -r notebooks/* docs/notebooks

      - run: uv run mkdocs gh-deploy --force


