name: Continuous Integration and Deployment
on: 
  push: 
    branches: [ main ]
  pull_request:
  schedule:
    - cron:  "0 3 * * 1" # Run every Monday 3 am

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: install Tkinter
        run: sudo apt-get install python3-tk

      - name: set up env
        run: python -m pip install -e .[docs,dev]

      - name: run black
        run: black --check .

      - name: run isort
        run: isort .

      - name: run pylint for mdp folder
        run: pylint src/behavior_generation_lecture_python/mdp --errors-only

      - name: run mypy for mdp folder
        run: mypy src/behavior_generation_lecture_python/mdp

      - name: test
        env:
          DISPLAY: ":0.0"
        run: pytest

      - name: check coverage
        env:
          DISPLAY: ":0.0"
        run: pytest --cov=src --cov-fail-under=70

      - name: copy notebooks to docs folder
        run: cp -r notebooks/* docs/notebooks

      - name: build docs
        run: mkdocs build

  deploy-pages:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main'
    concurrency: deploy-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: set up env
        run: python -m pip install -e .[docs]

      - name: copy notebooks to docs folder
        run: cp -r notebooks/* docs/notebooks

      - run: mkdocs gh-deploy --force


