name: Continuous Integration
on: 
  push: 
    branches: [ main ]
  pull_request:
  schedule:
    - cron:  "0 3 * * 1" # Run every Monday 3 am

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.10"

      - name: Install tkinter for GUI
        run: sudo apt install python3-tk -y

      - name: Set up env
        run: uv sync --all-extras --frozen

      - name: Run ruff format
        run: uv run ruff format

      - name: Run ruff linter for mdp folder
        run: uv run ruff check src/behavior_generation_lecture_python/mdp

      - name: Run mypy for mdp folder
        run: uv run mypy src/behavior_generation_lecture_python/mdp

      - name: Test
        run: |
          export DISPLAY=:99
          Xvfb :99 &
          uv run pytest

      - name: Check coverage
        run: |
          export DISPLAY=:99
          Xvfb :99 &
          uv run pytest --cov=src --cov-fail-under=85

      - name: Copy notebooks to docs folder
        run: cp -r notebooks/* docs/notebooks

      - name: Build PR docs (including running the notebooks)
        run: |
          uv run ipython kernel install --user --name=behavior_generation_lecture
          uv run mkdocs build --site-dir site/pr-${{ github.event.pull_request.number }}

      - name: Deploy PR docs
        if: github.event_name == 'pull_request'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site/pr-${{ github.event.pull_request.number }}
          destination_dir: pr-${{ github.event.pull_request.number }} # Deploy to subdirectory
          publish_branch: gh-pages
          keep_files: true # Retain other content on gh-pages

      - name: Add PR comment with preview link
        if: github.event_name == 'pull_request'
        run: |
            echo "Deployed [https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr-${{ github.event.pull_request.number }}/](temporary docs)."



